settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: GoCity
  path: /home/rodrigo/go/src/github.com/rodrigo-brito/gocity
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - .vscode
    - .idea
