language: go

go: 1.13.x

before_install:
- go mod download

script:
- go test -race -cover -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)