version: '3'
services:
  api:
    image:  "golang:1.11"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/github.com/rodrigo-brito/gocity/gcs-credentials.json
    volumes:
      - "../:/go/src/github.com/rodrigo-brito/gocity"
    command: ["go", "run"]
  caddy:
    image: "abiosoft/caddy"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    links:
      - api